-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 16:01:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solideo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solideo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solideo` DEFAULT CHARACTER SET utf8 ;
USE `solideo` ;

-- -----------------------------------------------------
-- Table `solideo`.`sldo_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solideo`.`sldo_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auth` INT NOT NULL,
  `account` NVARCHAR(50) NOT NULL,
  `password` NVARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `email` NVARCHAR(50) NULL,
  `signdt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solideo`.`sldo_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solideo`.`sldo_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` NVARCHAR(50) NOT NULL,
  `description` NVARCHAR(4000) NOT NULL,
  `postdt` DATETIME NULL DEFAULT now(),
  `upddt` DATETIME NULL DEFAULT now(),
  `delyn` VARCHAR(2) NULL DEFAULT 'N',
  `uid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sldo_notice_sldo_user_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `fk_sldo_notice_sldo_user`
    FOREIGN KEY (`uid`)
    REFERENCES `solideo`.`sldo_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
